### ISSUE TITLE
http_conn was renamed to swift_conn

### ISSUE THREAD

**Issue by ergofriend** [dennisv/django-storage-swift#106]
```
>>> from django.core.files.storage import default_storage
>>> default_storage.http_conn
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python37\lib\site-packages\django\utils\functional.py", line 214, in inner
    return func(self._wrapped, *args)
AttributeError: 'SwiftStorage' object has no attribute 'http_conn'
```

```
>>> default_storage.swift_conn
<swiftclient.client.Connection object at 0x000001E679679C50>
```

**Comment by einarf** [comment]
Where is this a problem?

**Comment by ErgoFriend** [comment]
In the README
https://github.com/dennisv/django-storage-swift#use
